<?xml version="1.0" encoding="utf-8"?><Database Name="inf245g2" ContextNamespace="pe.edu.pucp.ferretin.model" Class="FerretinDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=inti.lab.inf.pucp.edu.pe;Initial Catalog=inf245g2;Persist Security Info=True;User ID=inf245g2usr" SettingsObjectName="pe.edu.pucp.ferretin.model.Properties.Settings" SettingsPropertyName="inf245g2ConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Tbl_Almacen" Member="Tiendas">
    <Type Name="Tienda">
      <Column Name="id" Type="System.Int16" DbType="SmallInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_abastecedor" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="direccion" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="codigo" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="telefono1" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="telefono2" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="fecCreacion" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="tipo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="estado" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="id_ubigeo" Type="System.String" DbType="Char(6)" CanBeNull="true" />
      <Column Name="codigoPostal" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="fecCierre" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="id_jefe" Type="System.String" DbType="Char(8)" CanBeNull="true" />
      <Association Name="Tienda_Tienda" Member="Tbl_Almacen2" ThisKey="id" OtherKey="id_abastecedor" Type="Tienda" />
      <Association Name="Tienda_Tbl_Almacen_Horario" Member="Tbl_Almacen_Horario" ThisKey="id" OtherKey="id_tienda" Type="Tbl_Almacen_Horario" />
      <Association Name="Tienda_Tbl_Empleado_Almacen" Member="Tbl_Empleado_Almacen" ThisKey="id" OtherKey="id_almacen" Type="Tbl_Empleado_Almacen" />
      <Association Name="Tienda_Tbl_Lote" Member="Tbl_Lote" ThisKey="id" OtherKey="id_almacen" Type="Tbl_Lote" />
      <Association Name="Tienda_Tbl_Producto_Almacen" Member="Tbl_Producto_Almacen" ThisKey="id" OtherKey="id_almacen" Type="Tbl_Producto_Almacen" />
      <Association Name="Tienda_Tbl_Solicitud_Abastecimiento" Member="Tbl_Solicitud_Abastecimiento" ThisKey="id" OtherKey="id_almacen" Type="Tbl_Solicitud_Abastecimiento" />
      <Association Name="Tienda_Tbl_Turno" Member="Tbl_Turno" ThisKey="id" OtherKey="id_almacen" Type="Tbl_Turno" />
      <Association Name="Tienda_Tbl_Movimiento" Member="Tbl_Movimiento" ThisKey="id" OtherKey="id_almacen_desde" Type="Movimiento" />
      <Association Name="Tienda_Tbl_Movimiento1" Member="Movimiento" ThisKey="id" OtherKey="id_almacen_hasta" Type="Movimiento" />
      <Association Name="Tienda_Tienda" Member="Tbl_Almacen1" ThisKey="id_abastecedor" OtherKey="id" Type="Tienda" IsForeignKey="true" />
      <Association Name="Tbl_Empleado_Tienda" Member="Tbl_Empleado" ThisKey="id_jefe" OtherKey="dni" Type="Tbl_Empleado" IsForeignKey="true" />
      <Association Name="UbigeoDistrito_Tienda" Member="UbigeoDistrito" Storage="_Tbl_Ubigeo_Distrito" ThisKey="id_ubigeo" OtherKey="id" Type="UbigeoDistrito" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_Venta_Producto" Member="Tbl_Venta_Producto">
    <Type Name="Tbl_Venta_Producto">
      <Column Name="id_venta" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="id_producto" Type="System.Int16" DbType="SmallInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="cantidad" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="montoParcial" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="precioPuntos" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Association Name="Tbl_Producto_Tbl_Venta_Producto" Member="Tbl_Producto" ThisKey="id_producto" OtherKey="id" Type="Tbl_Producto" IsForeignKey="true" />
      <Association Name="Tbl_Venta_Tbl_Venta_Producto" Member="Tbl_Venta" ThisKey="id_venta" OtherKey="id" Type="Tbl_Venta" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_Almacen_Horario" Member="Tbl_Almacen_Horario">
    <Type Name="Tbl_Almacen_Horario">
      <Column Name="id_dia" Type="System.Byte" DbType="TinyInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="id_tienda" Type="System.Int16" DbType="SmallInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="horaInicio" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="horaFin" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Association Name="Tienda_Tbl_Almacen_Horario" Member="Tienda" Storage="_Tbl_Almacen" ThisKey="id_tienda" OtherKey="id" Type="Tienda" IsForeignKey="true" />
      <Association Name="Tbl_Dia_Tbl_Almacen_Horario" Member="Tbl_Dia" ThisKey="id_dia" OtherKey="id" Type="Tbl_Dia" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_Cargo" Member="Tbl_Cargo">
    <Type Name="Tbl_Cargo">
      <Column Name="id" Type="System.Byte" DbType="TinyInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="sueldoBase" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="estado" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Tbl_Cargo_Tbl_Empleado_Almacen" Member="Tbl_Empleado_Almacen" ThisKey="id" OtherKey="id_cargo" Type="Tbl_Empleado_Almacen" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_Categoria" Member="Tbl_Categoria">
    <Type Name="Tbl_Categoria">
      <Column Name="id" Type="System.Int16" DbType="SmallInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_padre" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="nivel" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Association Name="Tbl_Categoria_Tbl_Categoria" Member="Tbl_Categoria2" ThisKey="id" OtherKey="id_padre" Type="Tbl_Categoria" />
      <Association Name="Tbl_Categoria_Tbl_Producto_Categoria" Member="Tbl_Producto_Categoria" ThisKey="id" OtherKey="id_categoria" Type="Tbl_Producto_Categoria" />
      <Association Name="Tbl_Categoria_Tbl_Categoria" Member="Tbl_Categoria1" ThisKey="id_padre" OtherKey="id" Type="Tbl_Categoria" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_Cliente" Member="Cliente">
    <Type Name="Cliente">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nroDoc" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="direccion" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="telefono1" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="telefono2" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="fecNacimiento" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="sexo" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="fecAfiliacion" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="contacto" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="puntosGanados" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="puntosUsados" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="puntosActual" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ultimaCompra" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="totalCompras" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="comentarios" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="id_ubigeo" Type="System.String" DbType="Char(6)" CanBeNull="true" />
      <Column Name="codigoPostal" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="tipoPersona" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="tipoDocumento" Type="System.String" DbType="Char(3)" CanBeNull="true" />
      <Column Name="apPaterno" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="apMaterno" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="dni_empleado_registro" Type="System.String" DbType="Char(8)" CanBeNull="true" />
      <Association Name="Cliente_Tbl_Proforma" Member="Tbl_Proforma" ThisKey="id" OtherKey="id_cliente" Type="Tbl_Proforma" />
      <Association Name="Cliente_Tbl_Venta" Member="Tbl_Venta" ThisKey="id" OtherKey="id_cliente" Type="Tbl_Venta" />
      <Association Name="Tbl_Empleado_Cliente" Member="Tbl_Empleado" ThisKey="dni_empleado_registro" OtherKey="dni" Type="Tbl_Empleado" IsForeignKey="true" />
      <Association Name="UbigeoDistrito_Cliente" Member="UbigeoDistrito" Storage="_Tbl_Ubigeo_Distrito" ThisKey="id_ubigeo" OtherKey="id" Type="UbigeoDistrito" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_Color" Member="Tbl_Color">
    <Type Name="Tbl_Color">
      <Column Name="id" Type="System.Int16" DbType="SmallInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Tbl_Color_Tbl_Producto_Color" Member="Tbl_Producto_Color" ThisKey="id" OtherKey="id_color" Type="Tbl_Producto_Color" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_Devolucion" Member="Tbl_Devolucion">
    <Type Name="Tbl_Devolucion">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="codigo" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="fecEmision" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="fecVecimiento" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="total" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="comentario" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="id_venta" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Association Name="Tbl_Devolucion_Tbl_Devolucion_Producto" Member="Tbl_Devolucion_Producto" ThisKey="id" OtherKey="id_devolucion" Type="Tbl_Devolucion_Producto" />
      <Association Name="Tbl_Devolucion_Tbl_Nota_Credito" Member="Tbl_Nota_Credito" ThisKey="id" OtherKey="id_devolucion" Type="Tbl_Nota_Credito" />
      <Association Name="Tbl_Venta_Tbl_Devolucion" Member="Tbl_Venta" ThisKey="id_venta" OtherKey="id" Type="Tbl_Venta" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_Devolucion_Producto" Member="Tbl_Devolucion_Producto">
    <Type Name="Tbl_Devolucion_Producto">
      <Column Name="id_devolucion" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="id_producto" Type="System.Int16" DbType="SmallInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="cantidad" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="monto" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Association Name="Tbl_Devolucion_Tbl_Devolucion_Producto" Member="Tbl_Devolucion" ThisKey="id_devolucion" OtherKey="id" Type="Tbl_Devolucion" IsForeignKey="true" />
      <Association Name="Tbl_Producto_Tbl_Devolucion_Producto" Member="Tbl_Producto" ThisKey="id_producto" OtherKey="id" Type="Tbl_Producto" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_Dia" Member="Tbl_Dia">
    <Type Name="Tbl_Dia">
      <Column Name="id" Type="System.Byte" DbType="TinyInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Association Name="Tbl_Dia_Tbl_Almacen_Horario" Member="Tbl_Almacen_Horario" ThisKey="id" OtherKey="id_dia" Type="Tbl_Almacen_Horario" />
      <Association Name="Tbl_Dia_Tbl_Turno" Member="Tbl_Turno" ThisKey="id" OtherKey="id_dia" Type="Tbl_Turno" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_Empleado" Member="Tbl_Empleado">
    <Type Name="Tbl_Empleado">
      <Column Name="dni" Type="System.String" DbType="Char(8) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="apPaterno" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="apMaterno" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="fecNacimiento" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="sexo" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="direccion" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="telefono1" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="telefono2" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="id_grado_instruccion" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="estado" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="codigoPostal" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="id_ubigeo" Type="System.String" DbType="Char(6)" CanBeNull="true" />
      <Column Name="codEmpleado" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="Tbl_Empleado_Tienda" Member="Tbl_Almacen" ThisKey="dni" OtherKey="id_jefe" Type="Tienda" />
      <Association Name="Tbl_Empleado_Cliente" Member="Cliente" Storage="_Tbl_Cliente" ThisKey="dni" OtherKey="dni_empleado_registro" Type="Cliente" />
      <Association Name="Tbl_Empleado_Tbl_Empleado_Almacen" Member="Tbl_Empleado_Almacen" ThisKey="dni" OtherKey="dni" Type="Tbl_Empleado_Almacen" />
      <Association Name="Tbl_Empleado_Tbl_Empleado_Turno" Member="Tbl_Empleado_Turno" ThisKey="dni" OtherKey="dni" Type="Tbl_Empleado_Turno" />
      <Association Name="Tbl_Empleado_Tbl_Usuario" Member="Tbl_Usuarios" ThisKey="dni" OtherKey="dni" Type="Tbl_Usuario" />
      <Association Name="Tbl_Grado_Instruccion_Tbl_Empleado" Member="Tbl_Grado_Instruccion" ThisKey="id_grado_instruccion" OtherKey="id" Type="Tbl_Grado_Instruccion" IsForeignKey="true" />
      <Association Name="UbigeoDistrito_Tbl_Empleado" Member="UbigeoDistrito" Storage="_Tbl_Ubigeo_Distrito" ThisKey="id_ubigeo" OtherKey="id" Type="UbigeoDistrito" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_Empleado_Almacen" Member="Tbl_Empleado_Almacen">
    <Type Name="Tbl_Empleado_Almacen">
      <Column Name="dni" Type="System.String" DbType="Char(8) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="id_cargo" Type="System.Byte" DbType="TinyInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="fecInicio" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="fecFin" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="sueldo" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="id_almacen" Type="System.Int16" DbType="SmallInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Tienda_Tbl_Empleado_Almacen" Member="Tienda" Storage="_Tbl_Almacen" ThisKey="id_almacen" OtherKey="id" Type="Tienda" IsForeignKey="true" />
      <Association Name="Tbl_Cargo_Tbl_Empleado_Almacen" Member="Tbl_Cargo" ThisKey="id_cargo" OtherKey="id" Type="Tbl_Cargo" IsForeignKey="true" />
      <Association Name="Tbl_Empleado_Tbl_Empleado_Almacen" Member="Tbl_Empleado" ThisKey="dni" OtherKey="dni" Type="Tbl_Empleado" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_Empleado_Turno" Member="Tbl_Empleado_Turno">
    <Type Name="Tbl_Empleado_Turno">
      <Column Name="dni" Type="System.String" DbType="Char(8) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="id_turno" Type="System.Int16" DbType="SmallInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Tbl_Empleado_Tbl_Empleado_Turno" Member="Tbl_Empleado" ThisKey="dni" OtherKey="dni" Type="Tbl_Empleado" IsForeignKey="true" />
      <Association Name="Tbl_Turno_Tbl_Empleado_Turno" Member="Tbl_Turno" ThisKey="id_turno" OtherKey="id" Type="Tbl_Turno" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_Grado_Instruccion" Member="Tbl_Grado_Instruccion">
    <Type Name="Tbl_Grado_Instruccion">
      <Column Name="id" Type="System.Byte" DbType="TinyInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="Tbl_Grado_Instruccion_Tbl_Empleado" Member="Tbl_Empleado" ThisKey="id" OtherKey="id_grado_instruccion" Type="Tbl_Empleado" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_Lote" Member="Tbl_Lote">
    <Type Name="Tbl_Lote">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="fecVencimiento" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="cantidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id_producto" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="id_almacen" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Association Name="Tienda_Tbl_Lote" Member="Tienda" Storage="_Tbl_Almacen" ThisKey="id_almacen" OtherKey="id" Type="Tienda" IsForeignKey="true" />
      <Association Name="Tbl_Producto_Tbl_Lote" Member="Tbl_Producto" ThisKey="id_producto" OtherKey="id" Type="Tbl_Producto" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_Material" Member="Tbl_Material">
    <Type Name="Tbl_Material">
      <Column Name="id" Type="System.Int16" DbType="SmallInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="Tbl_Material_Tbl_Producto" Member="Tbl_Producto" ThisKey="id" OtherKey="id_material_base" Type="Tbl_Producto" />
      <Association Name="Tbl_Material_Tbl_Producto1" Member="Tbl_Producto1" ThisKey="id" OtherKey="id_material_sec" Type="Tbl_Producto" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_Medio_Pago" Member="Tbl_Medio_Pago">
    <Type Name="Tbl_Medio_Pago">
      <Column Name="id" Type="System.Byte" DbType="TinyInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Tbl_Medio_Pago_Tbl_Venta_Medio_Pago" Member="Tbl_Venta_Medio_Pago" ThisKey="id" OtherKey="id_medio_pago" Type="Tbl_Venta_Medio_Pago" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_Menu" Member="Tbl_Menu">
    <Type Name="Tbl_Menu">
      <Column Name="id" Type="System.Int16" DbType="SmallInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_menu_padre" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Tbl_Menu_Tbl_Menu" Member="Tbl_Menu2" ThisKey="id" OtherKey="id_menu_padre" Type="Tbl_Menu" />
      <Association Name="Tbl_Menu_Tbl_Parametro" Member="Tbl_Parametro" ThisKey="id" OtherKey="id_menu" Type="Tbl_Parametro" />
      <Association Name="Tbl_Menu_Tbl_Perfil_Menu" Member="Tbl_Perfil_Menu" ThisKey="id" OtherKey="id_menu" Type="Tbl_Perfil_Menu" />
      <Association Name="Tbl_Menu_Tbl_Transaccion_Tipo" Member="Tbl_Transaccion_Tipo" ThisKey="id" OtherKey="id_menu" Type="Tbl_Transaccion_Tipo" />
      <Association Name="Tbl_Menu_Tbl_Menu" Member="Tbl_Menu1" ThisKey="id_menu_padre" OtherKey="id" Type="Tbl_Menu" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_Movimiento_Estado" Member="Movimiento_Estado">
    <Type Name="Movimiento_Estado">
      <Column Name="id" Type="System.Byte" DbType="TinyInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Association Name="Movimiento_Estado_Tbl_Movimiento" Member="Movimiento" ThisKey="id" OtherKey="id_estado" Type="Movimiento" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_Movimiento_Producto" Member="Movimiento_Producto">
    <Type Name="Movimiento_Producto">
      <Column Name="id_movimiento" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="id_producto" Type="System.Int16" DbType="SmallInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="cantidad" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Association Name="Tbl_Producto_Movimiento_Producto" Member="Tbl_Producto" ThisKey="id_producto" OtherKey="id" Type="Tbl_Producto" IsForeignKey="true" />
      <Association Name="Tbl_Movimiento_Movimiento_Producto" Member="Movimiento" ThisKey="id_movimiento" OtherKey="id" Type="Movimiento" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_Movimiento_Tipo" Member="Movimiento_Tipo">
    <Type Name="Movimiento_Tipo">
      <Column Name="id" Type="System.Int16" DbType="SmallInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="categoria" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="estado" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Movimiento_Tipo_Tbl_Movimiento" Member="Movimiento" ThisKey="id" OtherKey="id_tipo" Type="Movimiento" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_Nota_Credito" Member="Tbl_Nota_Credito">
    <Type Name="Tbl_Nota_Credito">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="codigo" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="fechaEmision" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="fechaVencimiento" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="importe" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="id_devolucion" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Association Name="Tbl_Devolucion_Tbl_Nota_Credito" Member="Tbl_Devolucion" ThisKey="id_devolucion" OtherKey="id" Type="Tbl_Devolucion" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_Parametro" Member="Tbl_Parametro">
    <Type Name="Tbl_Parametro">
      <Column Name="id" Type="System.Byte" DbType="TinyInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="valor" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="id_menu" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Association Name="Tbl_Menu_Tbl_Parametro" Member="Tbl_Menu" ThisKey="id_menu" OtherKey="id" Type="Tbl_Menu" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_Perfil" Member="Tbl_Perfil">
    <Type Name="Tbl_Perfil">
      <Column Name="id" Type="System.Int16" DbType="SmallInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="estado" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Association Name="Tbl_Perfil_Tbl_Perfil_Menu" Member="Tbl_Perfil_Menu" ThisKey="id" OtherKey="id_Perfil" Type="Tbl_Perfil_Menu" />
      <Association Name="Tbl_Perfil_Tbl_Usuario" Member="Tbl_Usuarios" ThisKey="id" OtherKey="id_perfil" Type="Tbl_Usuario" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_Perfil_Menu" Member="Tbl_Perfil_Menu">
    <Type Name="Tbl_Perfil_Menu">
      <Column Name="id_menu" Type="System.Int16" DbType="SmallInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="id_Perfil" Type="System.Int16" DbType="SmallInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="estado" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Tbl_Menu_Tbl_Perfil_Menu" Member="Tbl_Menu" ThisKey="id_menu" OtherKey="id" Type="Tbl_Menu" IsForeignKey="true" />
      <Association Name="Tbl_Perfil_Tbl_Perfil_Menu" Member="Tbl_Perfil" ThisKey="id_Perfil" OtherKey="id" Type="Tbl_Perfil" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_Producto" Member="Tbl_Producto">
    <Type Name="Tbl_Producto">
      <Column Name="id" Type="System.Int16" DbType="SmallInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="codigo" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="precioLista" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="id_material_base" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="id_material_sec" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="id_unidad_medida" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="estado" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="imagen" Type="System.Data.Linq.Binary" DbType="VarBinary(1)" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Tbl_Producto_Tbl_Venta_Producto" Member="Tbl_Venta_Producto" ThisKey="id" OtherKey="id_producto" Type="Tbl_Venta_Producto" />
      <Association Name="Tbl_Producto_Tbl_Devolucion_Producto" Member="Tbl_Devolucion_Producto" ThisKey="id" OtherKey="id_producto" Type="Tbl_Devolucion_Producto" />
      <Association Name="Tbl_Producto_Tbl_Lote" Member="Tbl_Lote" ThisKey="id" OtherKey="id_producto" Type="Tbl_Lote" />
      <Association Name="Tbl_Producto_Movimiento_Producto" Member="Movimiento_Producto" ThisKey="id" OtherKey="id_producto" Type="Movimiento_Producto" />
      <Association Name="Tbl_Producto_Tbl_Producto_Almacen" Member="Tbl_Producto_Almacen" ThisKey="id" OtherKey="id_producto" Type="Tbl_Producto_Almacen" />
      <Association Name="Tbl_Producto_Tbl_Producto_Categoria" Member="Tbl_Producto_Categoria" ThisKey="id" OtherKey="id_producto" Type="Tbl_Producto_Categoria" />
      <Association Name="Tbl_Producto_Tbl_Producto_Color" Member="Tbl_Producto_Color" ThisKey="id" OtherKey="id_producto" Type="Tbl_Producto_Color" />
      <Association Name="Tbl_Producto_Tbl_Solicitud_Abastecimiento_Producto" Member="Tbl_Solicitud_Abastecimiento_Producto" ThisKey="id" OtherKey="id_producto" Type="Tbl_Solicitud_Abastecimiento_Producto" />
      <Association Name="Tbl_Producto_Tbl_Documento_Compra_Producto" Member="Tbl_Documento_Compra_Productos" ThisKey="id" OtherKey="id_producto" Type="Tbl_Documento_Compra_Producto" />
      <Association Name="Tbl_Material_Tbl_Producto" Member="Tbl_Material" ThisKey="id_material_base" OtherKey="id" Type="Tbl_Material" IsForeignKey="true" />
      <Association Name="Tbl_Material_Tbl_Producto1" Member="Tbl_Material1" ThisKey="id_material_sec" OtherKey="id" Type="Tbl_Material" IsForeignKey="true" />
      <Association Name="Tbl_Unidad_Medida_Tbl_Producto" Member="Tbl_Unidad_Medida" ThisKey="id_unidad_medida" OtherKey="id" Type="Tbl_Unidad_Medida" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_Producto_Almacen" Member="Tbl_Producto_Almacen">
    <Type Name="Tbl_Producto_Almacen">
      <Column Name="id_almacen" Type="System.Int16" DbType="SmallInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="id_producto" Type="System.Int16" DbType="SmallInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="stock" Type="System.Decimal" DbType="Decimal(12,2)" CanBeNull="true" />
      <Column Name="stockMin" Type="System.Decimal" DbType="Decimal(12,2)" CanBeNull="true" />
      <Column Name="stockMax" Type="System.Decimal" DbType="Decimal(12,2)" CanBeNull="true" />
      <Column Name="descuento" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="puntos" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Association Name="Tienda_Tbl_Producto_Almacen" Member="Tienda" Storage="_Tbl_Almacen" ThisKey="id_almacen" OtherKey="id" Type="Tienda" IsForeignKey="true" />
      <Association Name="Tbl_Producto_Tbl_Producto_Almacen" Member="Tbl_Producto" ThisKey="id_producto" OtherKey="id" Type="Tbl_Producto" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_Producto_Categoria" Member="Tbl_Producto_Categoria">
    <Type Name="Tbl_Producto_Categoria">
      <Column Name="id_categoria" Type="System.Int16" DbType="SmallInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="id_producto" Type="System.Int16" DbType="SmallInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Tbl_Categoria_Tbl_Producto_Categoria" Member="Tbl_Categoria" ThisKey="id_categoria" OtherKey="id" Type="Tbl_Categoria" IsForeignKey="true" />
      <Association Name="Tbl_Producto_Tbl_Producto_Categoria" Member="Tbl_Producto" ThisKey="id_producto" OtherKey="id" Type="Tbl_Producto" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_Producto_Color" Member="Tbl_Producto_Color">
    <Type Name="Tbl_Producto_Color">
      <Column Name="id_producto" Type="System.Int16" DbType="SmallInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="id_color" Type="System.Int16" DbType="SmallInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Tbl_Color_Tbl_Producto_Color" Member="Tbl_Color" ThisKey="id_color" OtherKey="id" Type="Tbl_Color" IsForeignKey="true" />
      <Association Name="Tbl_Producto_Tbl_Producto_Color" Member="Tbl_Producto" ThisKey="id_producto" OtherKey="id" Type="Tbl_Producto" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_Proforma" Member="Tbl_Proforma">
    <Type Name="Tbl_Proforma">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="codigo" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="fecEmision" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="fecVencimiento" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="subTotal" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="total" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="igv" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="destinatario" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="mensaje" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="id_cliente" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="dni" Type="System.String" DbType="Char(8)" CanBeNull="true" />
      <Column Name="id_perfil" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Association Name="Cliente_Tbl_Proforma" Member="Cliente" Storage="_Tbl_Cliente" ThisKey="id_cliente" OtherKey="id" Type="Cliente" IsForeignKey="true" />
      <Association Name="Tbl_Usuario_Tbl_Proforma" Member="Tbl_Usuario" ThisKey="dni,id_perfil" OtherKey="dni,id_perfil" Type="Tbl_Usuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_Proveedor" Member="Tbl_Proveedor">
    <Type Name="Tbl_Proveedor">
      <Column Name="id" Type="System.Int16" DbType="SmallInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ruc" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="razonSoc" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="tipo" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="direccion" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="telefono" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="paginaWeb" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="contacto" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="contactoTlf" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="id_rubro" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="estado" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="id_ubigeo" Type="System.String" DbType="Char(6)" CanBeNull="true" />
      <Column Name="codigoPostal" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Association Name="Tbl_Proveedor_Tbl_Proveedor_Catalogo" Member="Tbl_Proveedor_Catalogo" ThisKey="id" OtherKey="id_proveedor" Type="Tbl_Proveedor_Catalogo" />
      <Association Name="Tbl_Proveedor_Tbl_Documento_Compra" Member="Tbl_Documento_Compras" ThisKey="id" OtherKey="id_proveedor" Type="Tbl_Documento_Compra" />
      <Association Name="Tbl_Rubro_Tbl_Proveedor" Member="Tbl_Rubro" ThisKey="id_rubro" OtherKey="id" Type="Tbl_Rubro" IsForeignKey="true" />
      <Association Name="UbigeoDistrito_Tbl_Proveedor" Member="UbigeoDistrito" Storage="_Tbl_Ubigeo_Distrito" ThisKey="id_ubigeo" OtherKey="id" Type="UbigeoDistrito" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_Proveedor_Catalogo" Member="Tbl_Proveedor_Catalogo">
    <Type Name="Tbl_Proveedor_Catalogo">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="producto" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="unidad" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="precio" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="tiempoEntrega" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="id_proveedor" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Association Name="Tbl_Proveedor_Tbl_Proveedor_Catalogo" Member="Tbl_Proveedor" ThisKey="id_proveedor" OtherKey="id" Type="Tbl_Proveedor" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_Rubro" Member="Tbl_Rubro">
    <Type Name="Tbl_Rubro">
      <Column Name="id" Type="System.Int16" DbType="SmallInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Association Name="Tbl_Rubro_Tbl_Proveedor" Member="Tbl_Proveedor" ThisKey="id" OtherKey="id_rubro" Type="Tbl_Proveedor" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_Solicitud_Abastecimiento" Member="Tbl_Solicitud_Abastecimiento">
    <Type Name="Tbl_Solicitud_Abastecimiento">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="codigo" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="fecha" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="id_almacen" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="id_estado" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Association Name="Tbl_Solicitud_Abastecimiento_Tbl_Solicitud_Abastecimiento_Producto" Member="Tbl_Solicitud_Abastecimiento_Producto" ThisKey="id" OtherKey="id" Type="Tbl_Solicitud_Abastecimiento_Producto" />
      <Association Name="Tienda_Tbl_Solicitud_Abastecimiento" Member="Tienda" Storage="_Tbl_Almacen" ThisKey="id_almacen" OtherKey="id" Type="Tienda" IsForeignKey="true" />
      <Association Name="Tbl_Solicitud_Abastecimiento_Estado_Tbl_Solicitud_Abastecimiento" Member="Tbl_Solicitud_Abastecimiento_Estado" ThisKey="id_estado" OtherKey="id" Type="Tbl_Solicitud_Abastecimiento_Estado" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_Solicitud_Abastecimiento_Estado" Member="Tbl_Solicitud_Abastecimiento_Estado">
    <Type Name="Tbl_Solicitud_Abastecimiento_Estado">
      <Column Name="id" Type="System.Byte" DbType="TinyInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Association Name="Tbl_Solicitud_Abastecimiento_Estado_Tbl_Solicitud_Abastecimiento" Member="Tbl_Solicitud_Abastecimiento" ThisKey="id" OtherKey="id_estado" Type="Tbl_Solicitud_Abastecimiento" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_Solicitud_Abastecimiento_Producto" Member="Tbl_Solicitud_Abastecimiento_Producto">
    <Type Name="Tbl_Solicitud_Abastecimiento_Producto">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="id_producto" Type="System.Int16" DbType="SmallInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="cantidad" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="cantidadAtendida" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="cantidadRestante" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="estado" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Tbl_Producto_Tbl_Solicitud_Abastecimiento_Producto" Member="Tbl_Producto" ThisKey="id_producto" OtherKey="id" Type="Tbl_Producto" IsForeignKey="true" />
      <Association Name="Tbl_Solicitud_Abastecimiento_Tbl_Solicitud_Abastecimiento_Producto" Member="Tbl_Solicitud_Abastecimiento" ThisKey="id" OtherKey="id" Type="Tbl_Solicitud_Abastecimiento" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_Transaccion" Member="Tbl_Transaccion">
    <Type Name="Tbl_Transaccion">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fecha" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="nroIP" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="nroMAC" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="dni" Type="System.String" DbType="Char(8)" CanBeNull="true" />
      <Column Name="id_perfil" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="id_tipo_transaccion" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Association Name="Tbl_Transaccion_Tipo_Tbl_Transaccion" Member="Tbl_Transaccion_Tipo" ThisKey="id_tipo_transaccion" OtherKey="id" Type="Tbl_Transaccion_Tipo" IsForeignKey="true" />
      <Association Name="Tbl_Usuario_Tbl_Transaccion" Member="Tbl_Usuario" ThisKey="dni,id_perfil" OtherKey="dni,id_perfil" Type="Tbl_Usuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_Transaccion_Tipo" Member="Tbl_Transaccion_Tipo">
    <Type Name="Tbl_Transaccion_Tipo">
      <Column Name="id" Type="System.Int16" DbType="SmallInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="id_menu" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Association Name="Tbl_Transaccion_Tipo_Tbl_Transaccion" Member="Tbl_Transaccion" ThisKey="id" OtherKey="id_tipo_transaccion" Type="Tbl_Transaccion" />
      <Association Name="Tbl_Menu_Tbl_Transaccion_Tipo" Member="Tbl_Menu" ThisKey="id_menu" OtherKey="id" Type="Tbl_Menu" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_Turno" Member="Tbl_Turno">
    <Type Name="Tbl_Turno">
      <Column Name="id" Type="System.Int16" DbType="SmallInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="horaInicio" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="horaFin" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="duracion" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="estado" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="id_almacen" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="id_dia" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Association Name="Tbl_Turno_Tbl_Empleado_Turno" Member="Tbl_Empleado_Turno" ThisKey="id" OtherKey="id_turno" Type="Tbl_Empleado_Turno" />
      <Association Name="Tienda_Tbl_Turno" Member="Tienda" Storage="_Tbl_Almacen" ThisKey="id_almacen" OtherKey="id" Type="Tienda" IsForeignKey="true" />
      <Association Name="Tbl_Dia_Tbl_Turno" Member="Tbl_Dia" ThisKey="id_dia" OtherKey="id" Type="Tbl_Dia" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_Ubigeo_Departamento" Member="UbigeoDepartamento">
    <Type Name="UbigeoDepartamento">
      <Column Name="id" Type="System.String" DbType="Char(2) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Association Name="UbigeoDepartamento_UbigeoProvincia" Member="UbigeoProvincia" Storage="_Tbl_Ubigeo_Provincia" ThisKey="id" OtherKey="id_ubig_departamento" Type="UbigeoProvincia" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_Ubigeo_Distrito" Member="UbigeoDistrito">
    <Type Name="UbigeoDistrito">
      <Column Name="id" Type="System.String" DbType="Char(6) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="id_ubig_provincia" Type="System.String" DbType="Char(4)" CanBeNull="true" />
      <Association Name="UbigeoDistrito_Tienda" Member="Tbl_Almacen" ThisKey="id" OtherKey="id_ubigeo" Type="Tienda" />
      <Association Name="UbigeoDistrito_Cliente" Member="Cliente" Storage="_Tbl_Cliente" ThisKey="id" OtherKey="id_ubigeo" Type="Cliente" />
      <Association Name="UbigeoDistrito_Tbl_Empleado" Member="Tbl_Empleado" ThisKey="id" OtherKey="id_ubigeo" Type="Tbl_Empleado" />
      <Association Name="UbigeoDistrito_Tbl_Proveedor" Member="Tbl_Proveedor" ThisKey="id" OtherKey="id_ubigeo" Type="Tbl_Proveedor" />
      <Association Name="UbigeoProvincia_UbigeoDistrito" Member="UbigeoProvincia" Storage="_Tbl_Ubigeo_Provincia" ThisKey="id_ubig_provincia" OtherKey="id" Type="UbigeoProvincia" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_Ubigeo_Provincia" Member="UbigeoProvincia">
    <Type Name="UbigeoProvincia">
      <Column Name="id" Type="System.String" DbType="Char(4) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="id_ubig_departamento" Type="System.String" DbType="Char(2)" CanBeNull="true" />
      <Association Name="UbigeoProvincia_UbigeoDistrito" Member="UbigeoDistrito" Storage="_Tbl_Ubigeo_Distrito" ThisKey="id" OtherKey="id_ubig_provincia" Type="UbigeoDistrito" />
      <Association Name="UbigeoDepartamento_UbigeoProvincia" Member="UbigeoDepartamento" Storage="_Tbl_Ubigeo_Departamento" ThisKey="id_ubig_departamento" OtherKey="id" Type="UbigeoDepartamento" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_Unidad_Medida" Member="Tbl_Unidad_Medida">
    <Type Name="Tbl_Unidad_Medida">
      <Column Name="id" Type="System.Int16" DbType="SmallInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="abreviatura" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Association Name="Tbl_Unidad_Medida_Tbl_Producto" Member="Tbl_Producto" ThisKey="id" OtherKey="id_unidad_medida" Type="Tbl_Producto" />
      <Association Name="Tbl_Unidad_Medida_Tbl_Documento_Compra_Producto" Member="Tbl_Documento_Compra_Productos" ThisKey="id" OtherKey="id_unidad" Type="Tbl_Documento_Compra_Producto" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_Venta" Member="Tbl_Venta">
    <Type Name="Tbl_Venta">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="codigo" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="puntosCanjeados" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="subTotal" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="igv" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="total" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="fecha" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="nroDocumento" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="tipoDocumento" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="id_cliente" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="dni" Type="System.String" DbType="Char(8)" CanBeNull="true" />
      <Column Name="id_perfil" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Association Name="Tbl_Venta_Tbl_Venta_Producto" Member="Tbl_Venta_Producto" ThisKey="id" OtherKey="id_venta" Type="Tbl_Venta_Producto" />
      <Association Name="Tbl_Venta_Tbl_Devolucion" Member="Tbl_Devolucion" ThisKey="id" OtherKey="id_venta" Type="Tbl_Devolucion" />
      <Association Name="Tbl_Venta_Tbl_Venta_Medio_Pago" Member="Tbl_Venta_Medio_Pago" ThisKey="id" OtherKey="id_venta" Type="Tbl_Venta_Medio_Pago" />
      <Association Name="Cliente_Tbl_Venta" Member="Cliente" Storage="_Tbl_Cliente" ThisKey="id_cliente" OtherKey="id" Type="Cliente" IsForeignKey="true" />
      <Association Name="Tbl_Usuario_Tbl_Venta" Member="Tbl_Usuario" ThisKey="dni,id_perfil" OtherKey="dni,id_perfil" Type="Tbl_Usuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_Venta_Medio_Pago" Member="Tbl_Venta_Medio_Pago">
    <Type Name="Tbl_Venta_Medio_Pago">
      <Column Name="id_venta" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="id_medio_pago" Type="System.Byte" DbType="TinyInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="monto" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Association Name="Tbl_Medio_Pago_Tbl_Venta_Medio_Pago" Member="Tbl_Medio_Pago" ThisKey="id_medio_pago" OtherKey="id" Type="Tbl_Medio_Pago" IsForeignKey="true" />
      <Association Name="Tbl_Venta_Tbl_Venta_Medio_Pago" Member="Tbl_Venta" ThisKey="id_venta" OtherKey="id" Type="Tbl_Venta" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_Usuario" Member="Tbl_Usuarios">
    <Type Name="Tbl_Usuario">
      <Column Name="dni" Type="System.String" DbType="Char(8) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="contrasena" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="id_perfil" Type="System.Int16" DbType="SmallInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="estado" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Tbl_Usuario_Tbl_Proforma" Member="Tbl_Proformas" ThisKey="dni,id_perfil" OtherKey="dni,id_perfil" Type="Tbl_Proforma" />
      <Association Name="Tbl_Usuario_Tbl_Transaccion" Member="Tbl_Transaccions" ThisKey="dni,id_perfil" OtherKey="dni,id_perfil" Type="Tbl_Transaccion" />
      <Association Name="Tbl_Usuario_Tbl_Venta" Member="Tbl_Ventas" ThisKey="dni,id_perfil" OtherKey="dni,id_perfil" Type="Tbl_Venta" />
      <Association Name="Tbl_Usuario_Tbl_Documento_Compra" Member="Tbl_Documento_Compras" ThisKey="dni,id_perfil" OtherKey="dni_ingreso,id_perfil_ingreso" Type="Tbl_Documento_Compra" />
      <Association Name="Tbl_Usuario_Tbl_Documento_Compra1" Member="Tbl_Documento_Compras1" ThisKey="dni,id_perfil" OtherKey="dni_aprobacion,id_perfil_aprobacion" Type="Tbl_Documento_Compra" />
      <Association Name="Tbl_Empleado_Tbl_Usuario" Member="Tbl_Empleado" ThisKey="dni" OtherKey="dni" Type="Tbl_Empleado" IsForeignKey="true" />
      <Association Name="Tbl_Perfil_Tbl_Usuario" Member="Tbl_Perfil" ThisKey="id_perfil" OtherKey="id" Type="Tbl_Perfil" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_Documento_Compra" Member="Tbl_Documento_Compras">
    <Type Name="Tbl_Documento_Compra">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_cotizacion" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="codigo" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="fechaEmision" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="fechaVencimiento" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="subTotal" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="igv" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="total" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="nroFactura" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="id_proveedor" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="id_perfil_aprobacion" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="id_perfil_ingreso" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="dni_aprobacion" Type="System.String" DbType="Char(8)" CanBeNull="true" />
      <Column Name="dni_ingreso" Type="System.String" DbType="Char(8)" CanBeNull="true" />
      <Column Name="tipo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="id_estado" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Association Name="Tbl_Documento_Compra_Tbl_Documento_Compra" Member="Tbl_Documento_Compras" ThisKey="id" OtherKey="id_cotizacion" Type="Tbl_Documento_Compra" />
      <Association Name="Tbl_Documento_Compra_Tbl_Documento_Compra_Producto" Member="Tbl_Documento_Compra_Productos" ThisKey="id" OtherKey="id_documento_compra" Type="Tbl_Documento_Compra_Producto" />
      <Association Name="Tbl_Usuario_Tbl_Documento_Compra" Member="Tbl_Usuario" ThisKey="dni_ingreso,id_perfil_ingreso" OtherKey="dni,id_perfil" Type="Tbl_Usuario" IsForeignKey="true" />
      <Association Name="Tbl_Documento_Compra_Tbl_Documento_Compra" Member="Tbl_Documento_Compra1" ThisKey="id_cotizacion" OtherKey="id" Type="Tbl_Documento_Compra" IsForeignKey="true" />
      <Association Name="Tbl_Proveedor_Tbl_Documento_Compra" Member="Tbl_Proveedor" ThisKey="id_proveedor" OtherKey="id" Type="Tbl_Proveedor" IsForeignKey="true" />
      <Association Name="Tbl_Usuario_Tbl_Documento_Compra1" Member="Tbl_Usuario1" ThisKey="dni_aprobacion,id_perfil_aprobacion" OtherKey="dni,id_perfil" Type="Tbl_Usuario" IsForeignKey="true" />
      <Association Name="Tbl_Documento_Compra_Estado_Tbl_Documento_Compra" Member="Tbl_Documento_Compra_Estado" ThisKey="id_estado" OtherKey="id" Type="Tbl_Documento_Compra_Estado" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_Documento_Compra_Estado" Member="Tbl_Documento_Compra_Estados">
    <Type Name="Tbl_Documento_Compra_Estado">
      <Column Name="id" Type="System.Byte" DbType="TinyInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(35)" CanBeNull="true" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="tipo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Tbl_Documento_Compra_Estado_Tbl_Documento_Compra" Member="Tbl_Documento_Compras" ThisKey="id" OtherKey="id_estado" Type="Tbl_Documento_Compra" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_Documento_Compra_Producto" Member="Tbl_Documento_Compra_Productos">
    <Type Name="Tbl_Documento_Compra_Producto">
      <Column Name="id_documento_compra" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="id_producto" Type="System.Int16" DbType="SmallInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="id_unidad" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="precioUnit" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="cantidad" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="montoParcial" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Association Name="Tbl_Documento_Compra_Tbl_Documento_Compra_Producto" Member="Tbl_Documento_Compra" ThisKey="id_documento_compra" OtherKey="id" Type="Tbl_Documento_Compra" IsForeignKey="true" />
      <Association Name="Tbl_Producto_Tbl_Documento_Compra_Producto" Member="Tbl_Producto" ThisKey="id_producto" OtherKey="id" Type="Tbl_Producto" IsForeignKey="true" />
      <Association Name="Tbl_Unidad_Medida_Tbl_Documento_Compra_Producto" Member="Tbl_Unidad_Medida" ThisKey="id_unidad" OtherKey="id" Type="Tbl_Unidad_Medida" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_Movimiento" Member="Movimiento">
    <Type Name="Movimiento">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="codigo" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="fecha" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="comentario" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="id_tipo" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="id_almacen_desde" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="id_almacen_hasta" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="id_estado" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Association Name="Tbl_Movimiento_Movimiento_Producto" Member="Movimiento_Producto" ThisKey="id" OtherKey="id_movimiento" Type="Movimiento_Producto" />
      <Association Name="Tienda_Tbl_Movimiento" Member="Tienda" ThisKey="id_almacen_desde" OtherKey="id" Type="Tienda" IsForeignKey="true" />
      <Association Name="Tienda_Tbl_Movimiento1" Member="Tienda1" ThisKey="id_almacen_hasta" OtherKey="id" Type="Tienda" IsForeignKey="true" />
      <Association Name="Movimiento_Estado_Tbl_Movimiento" Member="Movimiento_Estado" ThisKey="id_estado" OtherKey="id" Type="Movimiento_Estado" IsForeignKey="true" />
      <Association Name="Movimiento_Tipo_Tbl_Movimiento" Member="Movimiento_Tipo" ThisKey="id_tipo" OtherKey="id" Type="Movimiento_Tipo" IsForeignKey="true" />
    </Type>
  </Table>
</Database>