<?xml version="1.0" encoding="utf-8"?><Database Name="inf245g2" Class="FerretinDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=inti.lab.inf.pucp.edu.pe;Initial Catalog=inf245g2;Persist Security Info=True;User ID=inf245g2dba" SettingsObjectName="pe.edu.pucp.ferretin.model.Properties.Settings" SettingsPropertyName="inf245g2ConnectionString2" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Cargo" Member="Cargo">
    <Type Name="Cargo">
      <Column Name="id" Type="System.Int16" DbType="SmallInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="sueldoBase" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="estado" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Cargo_EmpleadoTienda" Member="EmpleadoTienda" ThisKey="id" OtherKey="id_cargo" Type="EmpleadoTienda" />
    </Type>
  </Table>
  <Table Name="dbo.VentaProducto" Member="VentaProducto">
    <Type Name="VentaProducto">
      <Column Name="cantidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="montoParcial" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_venta" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="id_producto" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="canjeado" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="montoReal" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="descuento" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="descuentoPorcentaje" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="precioUnitario" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="puntosCanejado" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="puntosGanado" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="moneda" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Producto_VentaProducto" Member="Producto" ThisKey="id_producto" OtherKey="id" Type="Producto" IsForeignKey="true" />
      <Association Name="Venta_VentaProducto" Member="Venta" ThisKey="id_venta" OtherKey="id" Type="Venta" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Categoria" Member="Categoria">
    <Type Name="Categoria">
      <Column Name="id" Type="System.Int16" DbType="SmallInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_padre" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="nivel" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="recorrido_arbol" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Categoria_Categoria" Member="Categoria2" ThisKey="id" OtherKey="id_padre" Type="Categoria" />
      <Association Name="Categoria_ProductoCategoria" Member="ProductoCategoria" ThisKey="id" OtherKey="id_categoria" Type="ProductoCategoria" />
      <Association Name="Categoria_Categoria" Member="Categoria1" ThisKey="id_padre" OtherKey="id" Type="Categoria" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Cliente" Member="Cliente">
    <Type Name="Cliente">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nroDoc" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="direccion" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="telefono1" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="telefono2" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="fecNacimiento" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="sexo" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="fecAfiliacion" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="contacto" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="puntosGanados" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="puntosUsados" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="puntosActual" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ultimaCompra" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="totalCompras" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="comentarios" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="id_ubigeo" Type="System.String" DbType="Char(6)" CanBeNull="true" />
      <Column Name="imagen" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="tipoPersona" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="tipoDocumento" Type="System.String" DbType="Char(3)" CanBeNull="true" />
      <Column Name="apPaterno" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="apMaterno" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="id_empleado_registro" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Cliente_LoteVale" Member="LoteVale" ThisKey="id" OtherKey="id_cliente" Type="LoteVale" />
      <Association Name="Cliente_Proforma" Member="Proforma" ThisKey="id" OtherKey="id_cliente" Type="Proforma" />
      <Association Name="Cliente_Venta" Member="Venta" ThisKey="id" OtherKey="id_cliente" Type="Venta" />
      <Association Name="Empleado_Cliente" Member="Empleado" ThisKey="id_empleado_registro" OtherKey="id" Type="Empleado" IsForeignKey="true" />
      <Association Name="UbigeoDistrito_Cliente" Member="UbigeoDistrito" ThisKey="id_ubigeo" OtherKey="id" Type="UbigeoDistrito" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Color" Member="Color">
    <Type Name="Color">
      <Column Name="id" Type="System.Int16" DbType="SmallInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="abreviatura" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Association Name="Color_ProductoColor" Member="ProductoColor" ThisKey="id" OtherKey="id_color" Type="ProductoColor" />
    </Type>
  </Table>
  <Table Name="dbo.Devolucion" Member="Devolucion">
    <Type Name="Devolucion">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="codigo" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="fecEmision" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="total" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="comentario" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="id_venta" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="id_empleado" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="igv" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="subTotal" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Association Name="Devolucion_DevolucionProducto" Member="DevolucionProducto" ThisKey="id" OtherKey="id_devolucion" Type="DevolucionProducto" />
      <Association Name="Devolucion_NotaCredito" Member="NotaCredito" ThisKey="id" OtherKey="id_devolucion" Type="NotaCredito" />
      <Association Name="Empleado_Devolucion" Member="Empleado" ThisKey="id_empleado" OtherKey="id" Type="Empleado" IsForeignKey="true" />
      <Association Name="Venta_Devolucion" Member="Venta" ThisKey="id_venta" OtherKey="id" Type="Venta" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DevolucionProducto" Member="DevolucionProducto">
    <Type Name="DevolucionProducto">
      <Column Name="cantidad" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="monto" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_devolucion" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="id_producto" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="motivo" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="dardebaja" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Devolucion_DevolucionProducto" Member="Devolucion" ThisKey="id_devolucion" OtherKey="id" Type="Devolucion" IsForeignKey="true" />
      <Association Name="Producto_DevolucionProducto" Member="Producto" ThisKey="id_producto" OtherKey="id" Type="Producto" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Dia" Member="Dia">
    <Type Name="Dia">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Association Name="Dia_EmpleadoTurno" Member="EmpleadoTurno" ThisKey="id" OtherKey="id_dia" Type="EmpleadoTurno" />
    </Type>
  </Table>
  <Table Name="dbo.DocumentoCompra" Member="DocumentoCompra">
    <Type Name="DocumentoCompra">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_cotizacion" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="codigo" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="fechaEmision" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="fechaVencimiento" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="subTotal" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="igv" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="total" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="nroFactura" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="id_proveedor" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tipo" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="id_estado" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="id_usuario_aprobacion" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id_usuario_registro" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id_solicitud_compra" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="DocumentoCompra_DocumentoCompra" Member="DocumentoCompra2" ThisKey="id" OtherKey="id_cotizacion" Type="DocumentoCompra" />
      <Association Name="DocumentoCompra_DocumentoCompraProducto" Member="DocumentoCompraProducto" ThisKey="id" OtherKey="id_documento_compra" Type="DocumentoCompraProducto" />
      <Association Name="DocumentoCompra_GuiaRemision" Member="GuiaRemision" ThisKey="id" OtherKey="id_orden_compra" Type="GuiaRemision" />
      <Association Name="DocumentoCompra_DocumentoCompra" Member="DocumentoCompra1" ThisKey="id_cotizacion" OtherKey="id" Type="DocumentoCompra" IsForeignKey="true" />
      <Association Name="DocumentoCompraEstado_DocumentoCompra" Member="DocumentoCompraEstado" ThisKey="id_estado" OtherKey="id" Type="DocumentoCompraEstado" IsForeignKey="true" />
      <Association Name="Proveedor_DocumentoCompra" Member="Proveedor" ThisKey="id_proveedor" OtherKey="id" Type="Proveedor" IsForeignKey="true" />
      <Association Name="SolicitudCompra_DocumentoCompra" Member="SolicitudCompra" ThisKey="id_solicitud_compra" OtherKey="id" Type="SolicitudCompra" IsForeignKey="true" />
      <Association Name="Usuario_DocumentoCompra" Member="Usuario" ThisKey="id_usuario_aprobacion" OtherKey="id" Type="Usuario" IsForeignKey="true" />
      <Association Name="Usuario_DocumentoCompra1" Member="Usuario1" ThisKey="id_usuario_registro" OtherKey="id" Type="Usuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DocumentoCompraEstado" Member="DocumentoCompraEstado">
    <Type Name="DocumentoCompraEstado">
      <Column Name="id" Type="System.Int16" DbType="SmallInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(35)" CanBeNull="true" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="tipo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="DocumentoCompraEstado_DocumentoCompra" Member="DocumentoCompra" ThisKey="id" OtherKey="id_estado" Type="DocumentoCompra" />
    </Type>
  </Table>
  <Table Name="dbo.DocumentoCompraProducto" Member="DocumentoCompraProducto">
    <Type Name="DocumentoCompraProducto">
      <Column Name="precioUnit" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="cantidad" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="montoParcial" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_documento_compra" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="id_producto" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id_unidad_medida" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="estado" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="cantidadRestante" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Association Name="DocumentoCompraProducto_GuiaRemisionProducto" Member="GuiaRemisionProducto" ThisKey="id" OtherKey="id_guia_detalle" Type="GuiaRemisionProducto" />
      <Association Name="DocumentoCompra_DocumentoCompraProducto" Member="DocumentoCompra" ThisKey="id_documento_compra" OtherKey="id" Type="DocumentoCompra" IsForeignKey="true" />
      <Association Name="Producto_DocumentoCompraProducto" Member="Producto" ThisKey="id_producto" OtherKey="id" Type="Producto" IsForeignKey="true" />
      <Association Name="UnidadMedida_DocumentoCompraProducto" Member="UnidadMedida" ThisKey="id_unidad_medida" OtherKey="id" Type="UnidadMedida" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Empleado" Member="Empleado">
    <Type Name="Empleado">
      <Column Name="dni" Type="System.String" DbType="Char(8)" CanBeNull="true" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="apPaterno" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="apMaterno" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="fecNacimiento" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="sexo" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="direccion" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="telefono1" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="telefono2" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="estado" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="codEmpleado" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_ubigeo_distrito" Type="System.String" DbType="Char(6)" CanBeNull="true" />
      <Column Name="id_grado_instruccion" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="foto" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Empleado_Cliente" Member="Cliente" ThisKey="id" OtherKey="id_empleado_registro" Type="Cliente" />
      <Association Name="Empleado_Devolucion" Member="Devolucion" ThisKey="id" OtherKey="id_empleado" Type="Devolucion" />
      <Association Name="Empleado_EmpleadoTienda" Member="EmpleadoTienda" ThisKey="id" OtherKey="id_empleado" Type="EmpleadoTienda" />
      <Association Name="Empleado_EmpleadoTurno" Member="EmpleadoTurno" ThisKey="id" OtherKey="id_empleado" Type="EmpleadoTurno" />
      <Association Name="Empleado_Tienda" Member="Tienda" ThisKey="id" OtherKey="id_jefe" Type="Tienda" />
      <Association Name="Empleado_Usuario" Member="Usuario" ThisKey="id" OtherKey="id_empleado" Type="Usuario" />
      <Association Name="GradoInstruccion_Empleado" Member="GradoInstruccion" ThisKey="id_grado_instruccion" OtherKey="id" Type="GradoInstruccion" IsForeignKey="true" />
      <Association Name="UbigeoDistrito_Empleado" Member="UbigeoDistrito" ThisKey="id_ubigeo_distrito" OtherKey="id" Type="UbigeoDistrito" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.EmpleadoTienda" Member="EmpleadoTienda">
    <Type Name="EmpleadoTienda">
      <Column Name="fecInicio" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="fecFin" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="sueldo" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_cargo" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="id_empleado" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id_tienda" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="estado" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Cargo_EmpleadoTienda" Member="Cargo" ThisKey="id_cargo" OtherKey="id" Type="Cargo" IsForeignKey="true" />
      <Association Name="Empleado_EmpleadoTienda" Member="Empleado" ThisKey="id_empleado" OtherKey="id" Type="Empleado" IsForeignKey="true" />
      <Association Name="Tienda_EmpleadoTienda" Member="Tienda" ThisKey="id_tienda" OtherKey="id" Type="Tienda" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.EmpleadoTurno" Member="EmpleadoTurno">
    <Type Name="EmpleadoTurno">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_empleado" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id_turno" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id_dia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="estado" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Dia_EmpleadoTurno" Member="Dia" ThisKey="id_dia" OtherKey="id" Type="Dia" IsForeignKey="true" />
      <Association Name="Empleado_EmpleadoTurno" Member="Empleado" ThisKey="id_empleado" OtherKey="id" Type="Empleado" IsForeignKey="true" />
      <Association Name="Turno_EmpleadoTurno" Member="Turno" ThisKey="id_turno" OtherKey="id" Type="Turno" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.GradoInstruccion" Member="GradoInstruccion">
    <Type Name="GradoInstruccion">
      <Column Name="id" Type="System.Int16" DbType="SmallInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="GradoInstruccion_Empleado" Member="Empleado" ThisKey="id" OtherKey="id_grado_instruccion" Type="Empleado" />
    </Type>
  </Table>
  <Table Name="dbo.GuiaRemision" Member="GuiaRemision">
    <Type Name="GuiaRemision">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="codigo" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="fechaEmision" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="fechaRecepcion" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="estado" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id_orden_compra" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="id_almacen" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="GuiaRemision_GuiaRemisionProducto" Member="GuiaRemisionProducto" ThisKey="id" OtherKey="id_guia" Type="GuiaRemisionProducto" />
      <Association Name="DocumentoCompra_GuiaRemision" Member="DocumentoCompra" ThisKey="id_orden_compra" OtherKey="id" Type="DocumentoCompra" IsForeignKey="true" />
      <Association Name="Tienda_GuiaRemision" Member="Tienda" ThisKey="id_almacen" OtherKey="id" Type="Tienda" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.GuiaRemisionProducto" Member="GuiaRemisionProducto">
    <Type Name="GuiaRemisionProducto">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_guia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id_guia_detalle" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="cantidadRecibida" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Association Name="DocumentoCompraProducto_GuiaRemisionProducto" Member="DocumentoCompraProducto" ThisKey="id_guia_detalle" OtherKey="id" Type="DocumentoCompraProducto" IsForeignKey="true" />
      <Association Name="GuiaRemision_GuiaRemisionProducto" Member="GuiaRemision" ThisKey="id_guia" OtherKey="id" Type="GuiaRemision" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Lote" Member="Lote">
    <Type Name="Lote">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="fecVencimiento" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="cantidad" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="id_producto" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id_almacen" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="estado" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Association Name="Producto_Lote" Member="Producto" ThisKey="id_producto" OtherKey="id" Type="Producto" IsForeignKey="true" />
      <Association Name="Tienda_Lote" Member="Tienda" ThisKey="id_almacen" OtherKey="id" Type="Tienda" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LoteVale" Member="LoteVale">
    <Type Name="LoteVale">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="codigo" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="fechaEmision" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="fechaVencimiento" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="cantidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="moneda" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="monto" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="id_cliente" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="LoteVale_Vale" Member="Vale" ThisKey="id" OtherKey="id_lote_vale" Type="Vale" />
      <Association Name="Cliente_LoteVale" Member="Cliente" ThisKey="id_cliente" OtherKey="id" Type="Cliente" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Material" Member="Material">
    <Type Name="Material">
      <Column Name="id" Type="System.Int16" DbType="SmallInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="Material_Producto" Member="Producto" ThisKey="id" OtherKey="id_material_base" Type="Producto" />
      <Association Name="Material_Producto1" Member="Producto1" ThisKey="id" OtherKey="id_material_sec" Type="Producto" />
    </Type>
  </Table>
  <Table Name="dbo.MedioPago" Member="MedioPago">
    <Type Name="MedioPago">
      <Column Name="id" Type="System.Int16" DbType="SmallInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="MedioPago_VentaMedioPago" Member="VentaMedioPago" ThisKey="id" OtherKey="id_medio_pago" Type="VentaMedioPago" />
    </Type>
  </Table>
  <Table Name="dbo.Menu" Member="Menu">
    <Type Name="Menu">
      <Column Name="id" Type="System.Int16" DbType="SmallInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_menu_padre" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Menu_Menu" Member="Menu2" ThisKey="id" OtherKey="id_menu_padre" Type="Menu" />
      <Association Name="Menu_PerfilMenu" Member="PerfilMenu" ThisKey="id" OtherKey="id_menu" Type="PerfilMenu" />
      <Association Name="Menu_TransaccionTipo" Member="TransaccionTipo" ThisKey="id" OtherKey="id_menu" Type="TransaccionTipo" />
      <Association Name="Menu_Menu" Member="Menu1" ThisKey="id_menu_padre" OtherKey="id" Type="Menu" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Movimiento" Member="Movimiento">
    <Type Name="Movimiento">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="codigo" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="fecha" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="comentario" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="id_tipo" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="id_almacen_desde" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id_almacen_hasta" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id_estado" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Association Name="Movimiento_MovimientoProducto" Member="MovimientoProducto" ThisKey="id" OtherKey="id_movimiento" Type="MovimientoProducto" />
      <Association Name="MovimientoEstado_Movimiento" Member="MovimientoEstado" ThisKey="id_estado" OtherKey="id" Type="MovimientoEstado" IsForeignKey="true" />
      <Association Name="MovimientoTipo_Movimiento" Member="MovimientoTipo" ThisKey="id_tipo" OtherKey="id" Type="MovimientoTipo" IsForeignKey="true" />
      <Association Name="Tienda_Movimiento" Member="Tienda" ThisKey="id_almacen_desde" OtherKey="id" Type="Tienda" IsForeignKey="true" />
      <Association Name="Tienda_Movimiento1" Member="Tienda1" ThisKey="id_almacen_hasta" OtherKey="id" Type="Tienda" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MovimientoEstado" Member="MovimientoEstado">
    <Type Name="MovimientoEstado">
      <Column Name="id" Type="System.Int16" DbType="SmallInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="estado" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Association Name="MovimientoEstado_Movimiento" Member="Movimiento" ThisKey="id" OtherKey="id_estado" Type="Movimiento" />
    </Type>
  </Table>
  <Table Name="dbo.MovimientoProducto" Member="MovimientoProducto">
    <Type Name="MovimientoProducto">
      <Column Name="cantidad" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_movimiento" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="id_producto" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Movimiento_MovimientoProducto" Member="Movimiento" ThisKey="id_movimiento" OtherKey="id" Type="Movimiento" IsForeignKey="true" />
      <Association Name="Producto_MovimientoProducto" Member="Producto" ThisKey="id_producto" OtherKey="id" Type="Producto" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MovimientoTipo" Member="MovimientoTipo">
    <Type Name="MovimientoTipo">
      <Column Name="id" Type="System.Int16" DbType="SmallInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="categoria" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="estado" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="MovimientoTipo_Movimiento" Member="Movimiento" ThisKey="id" OtherKey="id_tipo" Type="Movimiento" />
    </Type>
  </Table>
  <Table Name="dbo.NotaCredito" Member="NotaCredito">
    <Type Name="NotaCredito">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="codigo" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="fechaEmision" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="fechaVencimiento" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="importe" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="id_devolucion" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="estado" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="NotaCredito_VentaMedioPago" Member="VentaMedioPago" ThisKey="id" OtherKey="notaCredito_id" Type="VentaMedioPago" />
      <Association Name="Devolucion_NotaCredito" Member="Devolucion" ThisKey="id_devolucion" OtherKey="id" Type="Devolucion" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Parametro" Member="Parametro">
    <Type Name="Parametro">
      <Column Name="id" Type="System.Int16" DbType="SmallInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="valor" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Perfil" Member="Perfil">
    <Type Name="Perfil">
      <Column Name="id" Type="System.Int16" DbType="SmallInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="estado" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Perfil_PerfilMenu" Member="PerfilMenu" ThisKey="id" OtherKey="id_perfil" Type="PerfilMenu" />
      <Association Name="Perfil_Usuario" Member="Usuario" ThisKey="id" OtherKey="id_perfil" Type="Usuario" />
    </Type>
  </Table>
  <Table Name="dbo.PerfilMenu" Member="PerfilMenu">
    <Type Name="PerfilMenu">
      <Column Name="estado" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_perfil" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="id_menu" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="id_PerfilMenuPadre" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="PerfilMenu_PerfilMenu" Member="PerfilMenu2" ThisKey="id" OtherKey="id_PerfilMenuPadre" Type="PerfilMenu" />
      <Association Name="PerfilMenu_PerfilMenu" Member="PerfilMenu1" ThisKey="id_PerfilMenuPadre" OtherKey="id" Type="PerfilMenu" IsForeignKey="true" />
      <Association Name="Menu_PerfilMenu" Member="Menu" ThisKey="id_menu" OtherKey="id" Type="Menu" IsForeignKey="true" />
      <Association Name="Perfil_PerfilMenu" Member="Perfil" ThisKey="id_perfil" OtherKey="id" Type="Perfil" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Producto" Member="Producto">
    <Type Name="Producto">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="codigo" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="precioLista" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="id_material_base" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="id_material_sec" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="id_unidad_medida" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="estado" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="imagen" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="moneda" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="precioPuntos" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ganarPuntos" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tipoServicio" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Producto_VentaProducto" Member="VentaProducto" ThisKey="id" OtherKey="id_producto" Type="VentaProducto" />
      <Association Name="Producto_DevolucionProducto" Member="DevolucionProducto" ThisKey="id" OtherKey="id_producto" Type="DevolucionProducto" />
      <Association Name="Producto_DocumentoCompraProducto" Member="DocumentoCompraProducto" ThisKey="id" OtherKey="id_producto" Type="DocumentoCompraProducto" />
      <Association Name="Producto_Lote" Member="Lote" ThisKey="id" OtherKey="id_producto" Type="Lote" />
      <Association Name="Producto_MovimientoProducto" Member="MovimientoProducto" ThisKey="id" OtherKey="id_producto" Type="MovimientoProducto" />
      <Association Name="Producto_ProductoAlmacen" Member="ProductoAlmacen" ThisKey="id" OtherKey="id_producto" Type="ProductoAlmacen" />
      <Association Name="Producto_ProductoCategoria" Member="ProductoCategoria" ThisKey="id" OtherKey="id_producto" Type="ProductoCategoria" />
      <Association Name="Producto_ProductoColor" Member="ProductoColor" ThisKey="id" OtherKey="id_producto" Type="ProductoColor" />
      <Association Name="Producto_ProductoPrecio" Member="ProductoPrecio" ThisKey="id" OtherKey="producto_id" Type="ProductoPrecio" />
      <Association Name="Producto_ProformaProducto" Member="ProformaProducto" ThisKey="id" OtherKey="producto_id" Type="ProformaProducto" />
      <Association Name="Producto_PromocionProducto" Member="PromocionProducto" ThisKey="id" OtherKey="producto_id" Type="PromocionProducto" />
      <Association Name="Producto_ProveedorProducto" Member="ProveedorProducto" ThisKey="id" OtherKey="id_producto" Type="ProveedorProducto" />
      <Association Name="Producto_SolicitudAbastecimientoProducto" Member="SolicitudAbastecimientoProducto" ThisKey="id" OtherKey="id_producto" Type="SolicitudAbastecimientoProducto" />
      <Association Name="Producto_SolicitudCompra" Member="SolicitudCompra" ThisKey="id" OtherKey="producto_id" Type="SolicitudCompra" />
      <Association Name="Material_Producto" Member="Material" ThisKey="id_material_base" OtherKey="id" Type="Material" IsForeignKey="true" />
      <Association Name="Material_Producto1" Member="Material1" ThisKey="id_material_sec" OtherKey="id" Type="Material" IsForeignKey="true" />
      <Association Name="UnidadMedida_Producto" Member="UnidadMedida" ThisKey="id_unidad_medida" OtherKey="id" Type="UnidadMedida" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProductoAlmacen" Member="ProductoAlmacen">
    <Type Name="ProductoAlmacen">
      <Column Name="stock" Type="System.Decimal" DbType="Decimal(12,2)" CanBeNull="true" />
      <Column Name="stockMin" Type="System.Decimal" DbType="Decimal(12,2)" CanBeNull="true" />
      <Column Name="stockMax" Type="System.Decimal" DbType="Decimal(12,2)" CanBeNull="true" />
      <Column Name="descuento" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="puntos" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_producto" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id_almacen" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="estado" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Association Name="Producto_ProductoAlmacen" Member="Producto" ThisKey="id_producto" OtherKey="id" Type="Producto" IsForeignKey="true" />
      <Association Name="Tienda_ProductoAlmacen" Member="Tienda" ThisKey="id_almacen" OtherKey="id" Type="Tienda" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProductoCategoria" Member="ProductoCategoria">
    <Type Name="ProductoCategoria">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_producto" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id_categoria" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Association Name="Categoria_ProductoCategoria" Member="Categoria" ThisKey="id_categoria" OtherKey="id" Type="Categoria" IsForeignKey="true" />
      <Association Name="Producto_ProductoCategoria" Member="Producto" ThisKey="id_producto" OtherKey="id" Type="Producto" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProductoColor" Member="ProductoColor">
    <Type Name="ProductoColor">
      <Column Name="id_producto" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="id_color" Type="System.Int16" DbType="SmallInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Color_ProductoColor" Member="Color" ThisKey="id_color" OtherKey="id" Type="Color" IsForeignKey="true" />
      <Association Name="Producto_ProductoColor" Member="Producto" ThisKey="id_producto" OtherKey="id" Type="Producto" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProductoPrecio" Member="ProductoPrecio">
    <Type Name="ProductoPrecio">
      <Column Name="precio" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="fechaRegistro" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="estado" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="producto_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="moneda" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="precioPuntos" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="Producto_ProductoPrecio" Member="Producto" ThisKey="producto_id" OtherKey="id" Type="Producto" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Proforma" Member="Proforma">
    <Type Name="Proforma">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="codigo" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="fecEmision" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="fecVencimiento" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="subTotal" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="total" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="igv" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="destinatario" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="mensaje" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="id_cliente" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id_usuario" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Proforma_ProformaProducto" Member="ProformaProducto" ThisKey="id" OtherKey="proforma_id" Type="ProformaProducto" />
      <Association Name="Cliente_Proforma" Member="Cliente" ThisKey="id_cliente" OtherKey="id" Type="Cliente" IsForeignKey="true" />
      <Association Name="Usuario_Proforma" Member="Usuario" ThisKey="id_usuario" OtherKey="id" Type="Usuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProformaProducto" Member="ProformaProducto">
    <Type Name="ProformaProducto">
      <Column Name="proforma_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="producto_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="cantidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="montoParcial" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="montoReal" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="descuento" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="descuentoPorcentaje" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="preciounitario" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Association Name="Producto_ProformaProducto" Member="Producto" ThisKey="producto_id" OtherKey="id" Type="Producto" IsForeignKey="true" />
      <Association Name="Proforma_ProformaProducto" Member="Proforma" ThisKey="proforma_id" OtherKey="id" Type="Proforma" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Promocion" Member="Promocion">
    <Type Name="Promocion">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="codigo" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="fechaDesde" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="fechaHasta" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="diasAplicables" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="estado" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Promocion_PromocionProducto" Member="PromocionProducto" ThisKey="id" OtherKey="promocion_id" Type="PromocionProducto" />
      <Association Name="Promocion_PromocionTienda" Member="PromocionTienda" ThisKey="id" OtherKey="promocion_id" Type="PromocionTienda" />
    </Type>
  </Table>
  <Table Name="dbo.PromocionProducto" Member="PromocionProducto">
    <Type Name="PromocionProducto">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="promocion_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="producto_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="descuento" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="cantMulUnidades" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="maxPromVenta" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="stockTotal" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="stockActual" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Producto_PromocionProducto" Member="Producto" ThisKey="producto_id" OtherKey="id" Type="Producto" IsForeignKey="true" />
      <Association Name="Promocion_PromocionProducto" Member="Promocion" ThisKey="promocion_id" OtherKey="id" Type="Promocion" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PromocionTienda" Member="PromocionTienda">
    <Type Name="PromocionTienda">
      <Column Name="promocion_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tienda_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="activo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="Promocion_PromocionTienda" Member="Promocion" ThisKey="promocion_id" OtherKey="id" Type="Promocion" IsForeignKey="true" />
      <Association Name="Tienda_PromocionTienda" Member="Tienda" ThisKey="tienda_id" OtherKey="id" Type="Tienda" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Proveedor" Member="Proveedor">
    <Type Name="Proveedor">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ruc" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="razonSoc" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="tipo" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="direccion" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="telefono" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="paginaWeb" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="contacto" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="contactoTlf" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="id_rubro" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="estado" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id_ubigeo" Type="System.String" DbType="Char(6)" CanBeNull="true" />
      <Column Name="codigoPostal" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Association Name="Proveedor_DocumentoCompra" Member="DocumentoCompra" ThisKey="id" OtherKey="id_proveedor" Type="DocumentoCompra" />
      <Association Name="Proveedor_ProveedorCatalogo" Member="ProveedorCatalogo" ThisKey="id" OtherKey="id_proveedor" Type="ProveedorCatalogo" />
      <Association Name="Proveedor_ProveedorProducto" Member="ProveedorProducto" ThisKey="id" OtherKey="id_proveedor" Type="ProveedorProducto" />
      <Association Name="Proveedor_SolicitudCompra" Member="SolicitudCompra" ThisKey="id" OtherKey="proveedor_id" Type="SolicitudCompra" />
      <Association Name="Rubro_Proveedor" Member="Rubro" ThisKey="id_rubro" OtherKey="id" Type="Rubro" IsForeignKey="true" />
      <Association Name="UbigeoDistrito_Proveedor" Member="UbigeoDistrito" ThisKey="id_ubigeo" OtherKey="id" Type="UbigeoDistrito" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProveedorCatalogo" Member="ProveedorCatalogo">
    <Type Name="ProveedorCatalogo">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="producto" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="unidad" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="precio" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="tiempoEntrega" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="id_proveedor" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="estado" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Association Name="Proveedor_ProveedorCatalogo" Member="Proveedor" ThisKey="id_proveedor" OtherKey="id" Type="Proveedor" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProveedorProducto" Member="ProveedorProducto">
    <Type Name="ProveedorProducto">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_proveedor" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id_producto" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id_unidad" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="precio" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="tiempoEntrega" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="estado" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Producto_ProveedorProducto" Member="Producto" ThisKey="id_producto" OtherKey="id" Type="Producto" IsForeignKey="true" />
      <Association Name="Proveedor_ProveedorProducto" Member="Proveedor" ThisKey="id_proveedor" OtherKey="id" Type="Proveedor" IsForeignKey="true" />
      <Association Name="UnidadMedida_ProveedorProducto" Member="UnidadMedida" ThisKey="id_unidad" OtherKey="id" Type="UnidadMedida" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Rubro" Member="Rubro">
    <Type Name="Rubro">
      <Column Name="id" Type="System.Int16" DbType="SmallInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Association Name="Rubro_Proveedor" Member="Proveedor" ThisKey="id" OtherKey="id_rubro" Type="Proveedor" />
    </Type>
  </Table>
  <Table Name="dbo.SolicitudAbastecimiento" Member="SolicitudAbastecimiento">
    <Type Name="SolicitudAbastecimiento">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="codigo" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="fecha" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="id_almacen" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id_estado" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Association Name="SolicitudAbastecimiento_SolicitudAbastecimientoProducto" Member="SolicitudAbastecimientoProducto" ThisKey="id" OtherKey="id_solicitud_abastecimiento" Type="SolicitudAbastecimientoProducto" />
      <Association Name="SolicitudAbastecimientoEstado_SolicitudAbastecimiento" Member="SolicitudAbastecimientoEstado" ThisKey="id_estado" OtherKey="id" Type="SolicitudAbastecimientoEstado" IsForeignKey="true" />
      <Association Name="Tienda_SolicitudAbastecimiento" Member="Tienda" ThisKey="id_almacen" OtherKey="id" Type="Tienda" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SolicitudAbastecimientoEstado" Member="SolicitudAbastecimientoEstado">
    <Type Name="SolicitudAbastecimientoEstado">
      <Column Name="id" Type="System.Int16" DbType="SmallInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Association Name="SolicitudAbastecimientoEstado_SolicitudAbastecimiento" Member="SolicitudAbastecimiento" ThisKey="id" OtherKey="id_estado" Type="SolicitudAbastecimiento" />
    </Type>
  </Table>
  <Table Name="dbo.SolicitudAbastecimientoProducto" Member="SolicitudAbastecimientoProducto">
    <Type Name="SolicitudAbastecimientoProducto">
      <Column Name="cantidad" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="cantidadAtendida" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="cantidadRestante" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="estado" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_solicitud_abastecimiento" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="id_producto" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Producto_SolicitudAbastecimientoProducto" Member="Producto" ThisKey="id_producto" OtherKey="id" Type="Producto" IsForeignKey="true" />
      <Association Name="SolicitudAbastecimiento_SolicitudAbastecimientoProducto" Member="SolicitudAbastecimiento" ThisKey="id_solicitud_abastecimiento" OtherKey="id" Type="SolicitudAbastecimiento" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SolicitudCompra" Member="SolicitudCompra">
    <Type Name="SolicitudCompra">
      <Column Name="producto_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="almacen_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="cantidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="estado" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="proveedor_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="SolicitudCompra_DocumentoCompra" Member="DocumentoCompra" ThisKey="id" OtherKey="id_solicitud_compra" Type="DocumentoCompra" />
      <Association Name="Producto_SolicitudCompra" Member="Producto" ThisKey="producto_id" OtherKey="id" Type="Producto" IsForeignKey="true" />
      <Association Name="Proveedor_SolicitudCompra" Member="Proveedor" ThisKey="proveedor_id" OtherKey="id" Type="Proveedor" IsForeignKey="true" />
      <Association Name="Tienda_SolicitudCompra" Member="Tienda" ThisKey="almacen_id" OtherKey="id" Type="Tienda" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tienda" Member="Tienda">
    <Type Name="Tienda">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_abastecedor" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="direccion" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="codigo" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="telefono1" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="telefono2" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="fecCreacion" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="tipo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="estado" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id_ubigeo" Type="System.String" DbType="Char(6)" CanBeNull="true" />
      <Column Name="codigoPostal" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="fecCierre" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="id_jefe" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="foto" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Tienda_EmpleadoTienda" Member="EmpleadoTienda" ThisKey="id" OtherKey="id_tienda" Type="EmpleadoTienda" />
      <Association Name="Tienda_GuiaRemision" Member="GuiaRemision" ThisKey="id" OtherKey="id_almacen" Type="GuiaRemision" />
      <Association Name="Tienda_Lote" Member="Lote" ThisKey="id" OtherKey="id_almacen" Type="Lote" />
      <Association Name="Tienda_Movimiento" Member="Movimiento" ThisKey="id" OtherKey="id_almacen_desde" Type="Movimiento" />
      <Association Name="Tienda_Movimiento1" Member="Movimiento1" ThisKey="id" OtherKey="id_almacen_hasta" Type="Movimiento" />
      <Association Name="Tienda_ProductoAlmacen" Member="ProductoAlmacen" ThisKey="id" OtherKey="id_almacen" Type="ProductoAlmacen" />
      <Association Name="Tienda_PromocionTienda" Member="PromocionTienda" ThisKey="id" OtherKey="tienda_id" Type="PromocionTienda" />
      <Association Name="Tienda_SolicitudAbastecimiento" Member="SolicitudAbastecimiento" ThisKey="id" OtherKey="id_almacen" Type="SolicitudAbastecimiento" />
      <Association Name="Tienda_SolicitudCompra" Member="SolicitudCompra" ThisKey="id" OtherKey="almacen_id" Type="SolicitudCompra" />
      <Association Name="Tienda_Tienda" Member="Tienda2" ThisKey="id" OtherKey="id_abastecedor" Type="Tienda" />
      <Association Name="Tienda_TiendaHorario" Member="TiendaHorario" ThisKey="id" OtherKey="id_almacen" Type="TiendaHorario" />
      <Association Name="Tienda_Tienda" Member="Tienda1" ThisKey="id_abastecedor" OtherKey="id" Type="Tienda" IsForeignKey="true" />
      <Association Name="Empleado_Tienda" Member="Empleado" ThisKey="id_jefe" OtherKey="id" Type="Empleado" IsForeignKey="true" />
      <Association Name="UbigeoDistrito_Tienda" Member="UbigeoDistrito" ThisKey="id_ubigeo" OtherKey="id" Type="UbigeoDistrito" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TiendaHorario" Member="TiendaHorario">
    <Type Name="TiendaHorario">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="horaInicio" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="horaFin" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="dia" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="id_almacen" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Tienda_TiendaHorario" Member="Tienda" ThisKey="id_almacen" OtherKey="id" Type="Tienda" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Transaccion" Member="Transaccion">
    <Type Name="Transaccion">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fecha" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="nroIP" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="nroMAC" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="id_tipo_transaccion" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="id_usuario" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TransaccionTipo_Transaccion" Member="TransaccionTipo" ThisKey="id_tipo_transaccion" OtherKey="id" Type="TransaccionTipo" IsForeignKey="true" />
      <Association Name="Usuario_Transaccion" Member="Usuario" ThisKey="id_usuario" OtherKey="id" Type="Usuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TransaccionTipo" Member="TransaccionTipo">
    <Type Name="TransaccionTipo">
      <Column Name="id" Type="System.Int16" DbType="SmallInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="id_menu" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Association Name="TransaccionTipo_Transaccion" Member="Transaccion" ThisKey="id" OtherKey="id_tipo_transaccion" Type="Transaccion" />
      <Association Name="Menu_TransaccionTipo" Member="Menu" ThisKey="id_menu" OtherKey="id" Type="Menu" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Turno" Member="Turno">
    <Type Name="Turno">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Association Name="Turno_EmpleadoTurno" Member="EmpleadoTurno" ThisKey="id" OtherKey="id_turno" Type="EmpleadoTurno" />
    </Type>
  </Table>
  <Table Name="dbo.UbigeoDepartamento" Member="UbigeoDepartamento">
    <Type Name="UbigeoDepartamento">
      <Column Name="id" Type="System.String" DbType="Char(2) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Association Name="UbigeoDepartamento_UbigeoProvincia" Member="UbigeoProvincia" ThisKey="id" OtherKey="id_ubig_departamento" Type="UbigeoProvincia" />
    </Type>
  </Table>
  <Table Name="dbo.UbigeoDistrito" Member="UbigeoDistrito">
    <Type Name="UbigeoDistrito">
      <Column Name="id" Type="System.String" DbType="Char(6) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="id_ubig_provincia" Type="System.String" DbType="Char(4)" CanBeNull="true" />
      <Association Name="UbigeoDistrito_Cliente" Member="Cliente" ThisKey="id" OtherKey="id_ubigeo" Type="Cliente" />
      <Association Name="UbigeoDistrito_Empleado" Member="Empleado" ThisKey="id" OtherKey="id_ubigeo_distrito" Type="Empleado" />
      <Association Name="UbigeoDistrito_Proveedor" Member="Proveedor" ThisKey="id" OtherKey="id_ubigeo" Type="Proveedor" />
      <Association Name="UbigeoDistrito_Tienda" Member="Tienda" ThisKey="id" OtherKey="id_ubigeo" Type="Tienda" />
      <Association Name="UbigeoProvincia_UbigeoDistrito" Member="UbigeoProvincia" ThisKey="id_ubig_provincia" OtherKey="id" Type="UbigeoProvincia" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UbigeoProvincia" Member="UbigeoProvincia">
    <Type Name="UbigeoProvincia">
      <Column Name="id" Type="System.String" DbType="Char(4) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="id_ubig_departamento" Type="System.String" DbType="Char(2)" CanBeNull="true" />
      <Association Name="UbigeoProvincia_UbigeoDistrito" Member="UbigeoDistrito" ThisKey="id" OtherKey="id_ubig_provincia" Type="UbigeoDistrito" />
      <Association Name="UbigeoDepartamento_UbigeoProvincia" Member="UbigeoDepartamento" ThisKey="id_ubig_departamento" OtherKey="id" Type="UbigeoDepartamento" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UnidadMedida" Member="UnidadMedida">
    <Type Name="UnidadMedida">
      <Column Name="id" Type="System.Int16" DbType="SmallInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="abreviatura" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Association Name="UnidadMedida_DocumentoCompraProducto" Member="DocumentoCompraProducto" ThisKey="id" OtherKey="id_unidad_medida" Type="DocumentoCompraProducto" />
      <Association Name="UnidadMedida_Producto" Member="Producto" ThisKey="id" OtherKey="id_unidad_medida" Type="Producto" />
      <Association Name="UnidadMedida_ProveedorProducto" Member="ProveedorProducto" ThisKey="id" OtherKey="id_unidad" Type="ProveedorProducto" />
    </Type>
  </Table>
  <Table Name="dbo.Usuario" Member="Usuario">
    <Type Name="Usuario">
      <Column Name="nombre" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="contrasena" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="estado" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="intentosCon" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="codUsuario" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="id_empleado" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id_perfil" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="logueado" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ultimoCambioContrasena" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Usuario_DocumentoCompra" Member="DocumentoCompra" ThisKey="id" OtherKey="id_usuario_aprobacion" Type="DocumentoCompra" />
      <Association Name="Usuario_DocumentoCompra1" Member="DocumentoCompra1" ThisKey="id" OtherKey="id_usuario_registro" Type="DocumentoCompra" />
      <Association Name="Usuario_Proforma" Member="Proforma" ThisKey="id" OtherKey="id_usuario" Type="Proforma" />
      <Association Name="Usuario_Transaccion" Member="Transaccion" ThisKey="id" OtherKey="id_usuario" Type="Transaccion" />
      <Association Name="Usuario_Venta" Member="Venta" ThisKey="id" OtherKey="id_usuario" Type="Venta" />
      <Association Name="Empleado_Usuario" Member="Empleado" ThisKey="id_empleado" OtherKey="id" Type="Empleado" IsForeignKey="true" />
      <Association Name="Perfil_Usuario" Member="Perfil" ThisKey="id_perfil" OtherKey="id" Type="Perfil" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Vale" Member="Vale">
    <Type Name="Vale">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="codigo" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="estado" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id_lote_vale" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Vale_VentaMedioPago" Member="VentaMedioPago" ThisKey="id" OtherKey="vale_id" Type="VentaMedioPago" />
      <Association Name="LoteVale_Vale" Member="LoteVale" ThisKey="id_lote_vale" OtherKey="id" Type="LoteVale" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Venta" Member="Venta">
    <Type Name="Venta">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="puntosCanjeados" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="subTotal" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="igv" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="total" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="fecha" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="nroDocumento" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="tipoDocumento" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id_cliente" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id_usuario" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="estado" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="puntosGanados" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="cobrado" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="diferencia" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="igvPorcentaje" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="tipoCambio" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="tipoMoneda" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Venta_VentaProducto" Member="VentaProducto" ThisKey="id" OtherKey="id_venta" Type="VentaProducto" />
      <Association Name="Venta_Devolucion" Member="Devolucion" ThisKey="id" OtherKey="id_venta" Type="Devolucion" />
      <Association Name="Venta_VentaMedioPago" Member="VentaMedioPago" ThisKey="id" OtherKey="id_venta" Type="VentaMedioPago" />
      <Association Name="Cliente_Venta" Member="Cliente" ThisKey="id_cliente" OtherKey="id" Type="Cliente" IsForeignKey="true" />
      <Association Name="Usuario_Venta" Member="Usuario" ThisKey="id_usuario" OtherKey="id" Type="Usuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.VentaMedioPago" Member="VentaMedioPago">
    <Type Name="VentaMedioPago">
      <Column Name="monto" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_venta" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="id_medio_pago" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="moneda" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="detalle" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="vale_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="notaCredito_id" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Association Name="NotaCredito_VentaMedioPago" Member="NotaCredito" ThisKey="notaCredito_id" OtherKey="id" Type="NotaCredito" IsForeignKey="true" />
      <Association Name="Vale_VentaMedioPago" Member="Vale" ThisKey="vale_id" OtherKey="id" Type="Vale" IsForeignKey="true" />
      <Association Name="MedioPago_VentaMedioPago" Member="MedioPago" ThisKey="id_medio_pago" OtherKey="id" Type="MedioPago" IsForeignKey="true" />
      <Association Name="Venta_VentaMedioPago" Member="Venta" ThisKey="id_venta" OtherKey="id" Type="Venta" IsForeignKey="true" />
    </Type>
  </Table>
</Database>